site_name: greed - A symbolic execution engine for EVM smart contract binaries
theme:
  name: readthedocs
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - tables
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - QuickStart: quickstart.md
  - Core Concepts: core.md
  - Advanced Topics: advanced.md
  - Options: options.md
  - Advice: advice.md
  - Examples: examples.md
  - Credits: credits.md
  - FAQ: faq.md
  - Modules:
    - greed.TAC.TAC_parser: modules/greed.TAC.TAC_parser.md
    - greed.TAC.base: modules/greed.TAC.base.md
    - greed.TAC.flow_ops: modules/greed.TAC.flow_ops.md
    - greed.TAC.gigahorse_ops: modules/greed.TAC.gigahorse_ops.md
    - greed.TAC.log_ops: modules/greed.TAC.log_ops.md
    - greed.TAC.math_ops: modules/greed.TAC.math_ops.md
    - greed.TAC.mem_ops: modules/greed.TAC.mem_ops.md
    - greed.TAC.special_ops: modules/greed.TAC.special_ops.md
    - greed.analyses.access_control_slots: modules/greed.analyses.access_control_slots.md
    - greed.analyses.slicing: modules/greed.analyses.slicing.md
    - greed.block: modules/greed.block.md
    - greed.cfg: modules/greed.cfg.md
    - greed.exploration_techniques.dfs: modules/greed.exploration_techniques.dfs.md
    - greed.exploration_techniques.directed_search: modules/greed.exploration_techniques.directed_search.md
    - greed.exploration_techniques.exploration_technique: modules/greed.exploration_techniques.exploration_technique.md
    - greed.exploration_techniques.heartbeat: modules/greed.exploration_techniques.heartbeat.md
    - greed.exploration_techniques.other: modules/greed.exploration_techniques.other.md
    - greed.exploration_techniques.prioritizer: modules/greed.exploration_techniques.prioritizer.md
    - greed.exploration_techniques.simgrviz: modules/greed.exploration_techniques.simgrviz.md
    - greed.factory: modules/greed.factory.md
    - greed.function: modules/greed.function.md
    - greed.memory.lambda_constraint: modules/greed.memory.lambda_constraint.md
    - greed.memory.lambda_memory: modules/greed.memory.lambda_memory.md
    - greed.memory.partial_concrete_storage: modules/greed.memory.partial_concrete_storage.md
    - greed.options: modules/greed.options.md
    - greed.project: modules/greed.project.md
    - greed.sha3: modules/greed.sha3.md
    - greed.sim_manager: modules/greed.sim_manager.md
    - greed.solver.shortcuts: modules/greed.solver.shortcuts.md
    - greed.solver.solver: modules/greed.solver.solver.md
    - greed.solver.yices2: modules/greed.solver.yices2.md
    - greed.state: modules/greed.state.md
    - greed.state_plugins.globals: modules/greed.state_plugins.globals.md
    - greed.state_plugins.inspect: modules/greed.state_plugins.inspect.md
    - greed.state_plugins.plugin: modules/greed.state_plugins.plugin.md
    - greed.state_plugins.sha_resolver: modules/greed.state_plugins.sha_resolver.md
    - greed.state_plugins.solver: modules/greed.state_plugins.solver.md
    - greed.utils.encoding: modules/greed.utils.encoding.md
    - greed.utils.exceptions: modules/greed.utils.exceptions.md
    - greed.utils.extra: modules/greed.utils.extra.md
    - greed.utils.files: modules/greed.utils.files.md
    